steps:
  - name: Codecov
  - uses: codecov/codecov-action@v1.0.6
  - uses: actions/checkout@master
    with:
      token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
      file: ./coverage.xml # optional
      flags: unittests # optional
      name: codecov-jest # optional
      fail_ci_if_error: false # optional (default = false)